# Generated by Django 2.2.1 on 2020-03-20 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('rating', models.IntegerField(db_column='rating')),
                ('photo', models.CharField(db_column='photo', max_length=255)),
            ],
            options={
                'db_table': 'masters',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=255)),
                ('photo', models.CharField(db_column='photo', max_length=255)),
                ('price', models.IntegerField(db_column='price')),
                ('masters', models.ManyToManyField(to='barbershop_server.Master')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('text', models.CharField(db_column='text', max_length=255)),
                ('rating', models.IntegerField(db_column='rating')),
                ('date', models.TimeField(db_column='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='barbershop_server.User')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
