# Generated by Django 2.2.1 on 2020-03-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(blank=True, related_name='services', related_query_name='service', to='barbershop_server.Master'),
        ),
    ]
