# Generated by Django 2.2.1 on 2020-03-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop_server', '0002_auto_20200320_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='masters',
            field=models.ManyToManyField(to='barbershop_server.Master'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbershop_server.Master')),
            ],
        ),
    ]
