# Generated by Django 2.2.1 on 2020-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop_server', '0003_auto_20200322_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
