# Generated by Django 2.2.1 on 2020-04-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop_server', '0004_auto_20200323_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
